version: '2'
services:

# 유레카 서버
  bnkRegSvr:
     image: tyn_networks/bnkRegSvr:bnkCloudOdsSample
     ports:
       - "8761:8761"
       
# 컨피그 서버       
  bnkConfigSvr:
      image: tyn_networks/bnkConfigSvr:bnkCloudOdsSample
      ports:
         - "8888:8888"
      environment:
         EUREKASERVER_URI: "http://bnkRegSvr:8761/eureka/"
         EUREKASERVER_PORT: "8761"
         ENCRYPT_KEY:       "q1w2e3r4t5A!S@D#F$"

# 나중에 설정  
#  database:
#      image: oracle:9.5
#      ports:
#      - "5432:5432"
#      environment:
#        - POSTGRES_USER=root
#        - POSTGRES_PASSWORD=1111
#        - POSTGRES_DB=oracle

# 서비스 서버, harang        
  harang:
      image: tyn_networks/harang:bnkCloudOdsSample
      ports:
        - "8080:8080"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8080"
        CONFIGSERVER_URI: "http://bnkConfigSvr:8888"
        EUREKASERVER_URI: "http://bnkRegSvr:8761/eureka/"
        EUREKASERVER_PORT:   "8761"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
        ENCRYPT_KEY:       "q1w2e3r4t5A!S@D#F$"
        
# 서비스 서버, concept                
  concept:
      image: tyn_networks/concept:bnkCloudOdsSample
      ports:
        - "8085:8085"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8085"
        CONFIGSERVER_URI: "http://bnkConfigSvr:8888"
        EUREKASERVER_URI: "http://bnkRegSvr:8761/eureka/"
        EUREKASERVER_PORT:   "8761"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
        ENCRYPT_KEY:       "q1w2e3r4t5A!S@D#F$"
        